window.EXTRA_EMOTIONS=(window.EXTRA_EMOTIONS||[]).concat([
["overthinking",["grüble","grueble","zerdenke","overthink"],["Du musst nicht jeden Gedanken zu Ende denken.","Manche Klarheit kommt erst, wenn Denken Pause macht."]],
["jealousy",["eifersucht","eifersüchtig","eifersuechtig","jealous"],["Eifersucht zeigt oft Angst, nicht Wahrheit.","Vergleiche sagen wenig über deinen Wert."]],
["anger",["wütend","wuetend","wut","zorn","angry"],["Wut zeigt oft, wo eine Grenze verletzt wurde.","Du darfst wütend sein, ohne dich von der Wut führen zu lassen."]],
["sadness",["traurig","traurigkeit","sad","weinen"],["Traurigkeit muss nicht sofort verschwinden.","Du darfst traurig sein, ohne alles erklären zu müssen."]],
["grief",["trauer","trauere","verlust","grief"],["Trauer hat keinen festen Zeitplan.","Was fehlt, darf wichtig bleiben."]],
["shame",["scham","schäme","schaeme","shame"],["Scham will dich verstecken. Wahrheit darf dich wieder hervorholen.","Ein Moment definiert nicht deinen ganzen Charakter."]],
["guilt",["schuld","schuldig","gewissen","guilt"],["Schuld kann ein Hinweis sein, aber kein Zuhause.","Verantwortung ist hilfreicher als Selbstbestrafung."]],
["regret",["bereue","reue","regret"],["Du kennst heute Dinge, die du damals nicht wusstest.","Reue kann Richtung geben, ohne dich festzuhalten."]],
["envy",["neid","neidisch","envy"],["Neid zeigt manchmal, was du selbst vermisst.","Das Leben anderer ist kein Maßstab für deinen Weg."]],
["frustration",["frustriert","frust","frustrated"],["Frust bedeutet nicht, dass du gescheitert bist.","Vielleicht brauchst du einen anderen Weg, nicht mehr Druck."]],
["disappointment",["enttäuscht","enttaeuscht","enttäuschung"],["Enttäuschung zeigt, dass dir etwas wichtig war.","Du darfst neu entscheiden, was du jetzt brauchst."]],
["confusion",["verwirrt","verwirrung","confused"],["Verwirrung ist oft ein Zwischenraum, kein Endzustand.","Du musst noch nicht alles verstehen."]],
["indecision",["unentschlossen","kann mich nicht entscheiden"],["Du brauchst nicht absolute Sicherheit für eine Entscheidung.","Welche Wahl bringt dir langfristig mehr Ruhe?"]],
["fear_failure",["angst zu scheitern","scheitern","versagen"],["Scheitern ist ein Ereignis, keine Identität.","Du musst nicht garantieren können, dass es klappt."]],
["fear_rejection",["ablehnung","zurückweisung","zurueckweisung"],["Ablehnung sagt nicht alles über deinen Wert.","Nicht jede verschlossene Tür war für dich bestimmt."]],
["fear_abandonment",["verlassen werden","verlustangst"],["Nähe wird nicht sicherer, wenn du dich selbst verlässt.","Angst vor Verlust ist noch kein Beweis für Verlust."]],
["fear_future",["angst vor morgen","zukunftsangst","was wenn"],["Morgen ist noch nicht hier.","Der nächste echte Schritt reicht."]],
["social_anxiety",["soziale angst","unter leute","social anxiety"],["Du musst nicht perfekt wirken, um dazugehören zu dürfen.","Ein kleiner Kontakt reicht für heute."]],
["performance_anxiety",["prüfung nervös","pruefung nervoes","vortrag nervös"],["Nervosität bedeutet nicht, dass du unvorbereitet bist.","Du musst nicht perfekt sein, nur präsent."]],
["imposter",["imposter","hochstapler","nicht verdient"],["Du musst dich nicht wie ein Profi fühlen, um etwas gut zu können.","Dein Platz ist nicht automatisch ein Irrtum."]],
["insecurity",["unsicher","unsicherheit","insecure"],["Unsicherheit ist ein Gefühl, keine Bewertung.","Sicherheit wächst oft erst unterwegs."]],
["low_confidence",["kein selbstvertrauen","traue mir nicht"],["Selbstvertrauen kommt oft nach dem Schritt, nicht davor.","Du brauchst heute nur genug Mut für einen kleinen Versuch."]],
["body_insecurity",["zu dick","zu dünn","zu duenn","hässlich","haesslich"],["Dein Körper ist mehr als etwas, das bewertet werden muss.","Du musst dich heute nicht schön finden, um freundlich mit dir zu sein."]],
["comparison",["vergleiche mich","vergleich","besser als ich"],["Du siehst bei anderen oft das Ergebnis und bei dir den ganzen Weg.","Dein Tempo muss nicht ihres sein."]],
["perfectionism",["perfektion","perfektionist","perfekt sein"],["Perfekt ist oft nur eine andere Form von Aufschieben.","Gut genug darf wirklich genug sein."]]
]);