window.EXTRA_EMOTIONS=(window.EXTRA_EMOTIONS||[]).concat([
["procrastination",["aufschieben","prokrastination","procrastinate"],["Mach es kleiner, nicht dramatischer.","Fünf Minuten zählen auch."]],
["motivation_low",["keine motivation","unmotiviert"],["Motivation ist nicht immer der Anfang.","Du brauchst heute keinen großen Antrieb."]],
["boredom",["langweilig","langeweile","bored"],["Langeweile kann Platz sein, nicht nur Leere.","Vielleicht braucht dein Kopf etwas Neues, nicht mehr Reiz."]],
["restlessness",["rastlos","ruhelose","restless"],["Nicht jede Unruhe braucht sofort Aktion.","Dein Körper darf langsamer werden als deine Gedanken."]],
["overstimulation",["überreizt","ueberreizt","zu viel input"],["Weniger Reize können gerade mehr helfen als mehr Lösungen.","Mach die Welt für zehn Minuten kleiner."]],
["irritability",["gereizt","genervt","reizbar"],["Gereiztheit ist oft Müdigkeit mit schärferer Stimme.","Vielleicht brauchst du Abstand, bevor du antwortest."]],
["resentment",["groll","nachtragend","resentment"],["Groll hält dich oft länger fest als die andere Person.","Eine Grenze kann hilfreicher sein als inneres Wiederholen."]],
["betrayal",["verraten","betrogen","betrayal"],["Verrat verändert Vertrauen, nicht deinen Wert.","Du darfst vorsichtiger werden, ohne hart zu werden."]],
["trust_issues",["vertraue niemandem","vertrauen fällt schwer"],["Vertrauen darf langsam wachsen.","Sicherheit entsteht auch durch beobachtetes Verhalten."]],
["heartache",["herzweh","herz tut weh","liebe tut weh"],["Dein Herz darf Zeit brauchen.","Schmerz ist nicht automatisch ein Zeichen, zurückzugehen."]],
["missing_someone",["ich vermisse","vermisse ihn","vermisse sie"],["Vermissen ist kein Auftrag zur Rückkehr.","Du kannst jemanden vermissen und trotzdem weitergehen."]],
["attachment",["kann nicht loslassen","klammere"],["Loslassen beginnt oft, bevor das Gefühl bereit ist.","Nähe sollte dich nicht von dir selbst entfernen."]],
["unrequited_love",["unerwiderte liebe","liebt mich nicht"],["Nicht erwiderte Liebe macht deine Gefühle nicht falsch.","Dein Herz verdient Gegenseitigkeit."]],
["breakup_recovery",["über ex hinweg","ueber ex hinweg","nach trennung"],["Heilung ist nicht linear.","Ein Rückfall in Erinnerungen ist kein Rückschritt."]],
["relationship_doubt",["beziehungszweifel","liebe ich ihn noch","liebe ich sie noch"],["Zweifel sind Informationen, keine sofortige Entscheidung.","Liebe allein beantwortet nicht jede Frage."]],
["conflict",["streit","konflikt","wir streiten"],["Im Streit geht es oft um mehr als den letzten Satz.","Du darfst eine Pause machen, bevor du weiterredest."]],
["boundaries",["grenzen","nein sagen"],["Eine Grenze braucht keine lange Rechtfertigung.","Nein ist ein vollständiger Satz."]],
["people_pleasing",["allen recht machen","people pleaser","kann nicht nein sagen"],["Du musst nicht überall angenehm sein, um liebenswert zu bleiben.","Ein Nein schützt manchmal ein ehrlicheres Ja."]],
["approval_seeking",["anerkennung","bestätigung","bestaetigung"],["Bestätigung von außen hält selten lange.","Du musst nicht von allen verstanden werden."]],
["feeling_unseen",["nicht gesehen","keiner sieht mich","unsichtbar"],["Nicht gesehen zu werden heißt nicht, dass du nichts zu sehen bist.","Vielleicht brauchst du andere Augen, nicht einen anderen Wert."]],
["feeling_unheard",["hört mir nicht zu","hoert mir nicht zu"],["Du darfst erwarten, dass man dir zuhört.","Wiederholen macht deine Wahrheit nicht weniger wahr."]],
["rejection",["abgewiesen","zurückgewiesen","zurueckgewiesen"],["Zurückweisung ist schmerzhaft, aber nicht endgültig über dich.","Ein Nein kann dich umleiten, ohne dich zu entwerten."]],
["failure",["gescheitert","versagt"],["Ein Ergebnis ist kein Urteil über dein ganzes Können.","Du kannst neu anfangen, ohne bei null zu sein."]],
["mistake",["fehler gemacht","falsch gemacht"],["Ein Fehler ist Information.","Du darfst korrigieren, ohne dich zu verurteilen."]],
["embarrassment",["blamiert","peinlich"],["Andere erinnern sich meist kürzer daran als du.","Du darfst menschlich gewesen sein."]]
);