const frame=document.getElementById('orb-frame');
frame.addEventListener('load',async()=>{
 const doc=frame.contentDocument;
 const css=doc.createElement('link');css.rel='stylesheet';css.href=new URL('level-2.css',location.href).href;doc.head.append(css);
 doc.querySelector('.shell').insertAdjacentHTML('afterbegin','<nav class="level-nav"><a href="index.html">Magic Orb</a><span>Level 2 · Test</span></nav>\n    ');
 doc.querySelector('#hint').insertAdjacentHTML('afterend','<p id="level-status" class="level-status" role="status">Die Kugel erinnert sich an deine Fragen auf diesem Gerät.</p>\n      <p id="level-echo" class="level-echo" aria-live="polite"></p>\n      <div class="level-actions"><button id="orb-mic" type="button">Erzählen</button><button id="orb-speak" type="button" aria-pressed="false">Stimme aus</button><button id="orb-again" type="button">Weiterfragen</button></div>\n      <details class="level-memory"><summary>Was die Kugel sich merkt</summary><p>Fragen bleiben nur in diesem Browser. Hinweise aus deinen Worten sind vorläufig; du kannst sie einzeln löschen. Geheimnisse in der verschlossenen Box werden nicht gespeichert.</p><div id="orb-memory"></div><button id="orb-forget" type="button">Alle Erinnerungen löschen</button><p>Freie KI-Antworten laufen mit einem lokalen Sprachmodell auf deinem Computer. Ohne passende Hardware verwendet die Kugel ihre vorhandenen Antworten und Erinnerungsregeln. Die Browser-Spracherkennung kann Audio an ihren Anbieter übertragen.</p><button id="orb-ai" type="button">Lokale KI aktivieren</button><p id="orb-ai-status" role="status">KI noch nicht geladen · Erinnerungsregeln aktiv.</p></details>\n\n      ');
 async function script(file){await new Promise((resolve,reject)=>{const s=doc.createElement('script');s.src=new URL(file,location.href).href;s.onload=resolve;s.onerror=reject;doc.body.append(s);});}
 try{await script('memory.js');await script('level-2.js');}catch{doc.getElementById('level-status').textContent='Level 2 konnte nicht geladen werden. Bitte die Seite neu laden.';}
});
